#ifndef <|PROJECT_DOWNCASE_IDENTIFIER|>_include_h__
#define <|PROJECT_DOWNCASE_IDENTIFIER|>_include_h__

// this is a global symbol that is exposed, which can be used to detect
// if this library is available

#define HAVE_INCLUDE_<|PROJECT_UPCASE_IDENTIFIER|>

/* DO:    #include this files in public headers.

   DONT:  #include this files in private headers.
          #include this file directly in sources.
          #import this file anywhere (except in import.h)
 */


/* This is a central include file to keep dependencies out of the library
   C files. It is usually included by .h files only.

   As the name "include.h" is standardized across mulle-sde projects,
   .c and .h files are now  motile. They can be moved to other projects and
   don't need to be edited.

   If you delete it, it will not be regenerated.
*/

/*
 * Include the header file generated by mulle-sde reflect.
 */

#include "_<|PROJECT_NAME|>-include.h"

#ifndef <|PROJECT_UPCASE_IDENTIFIER|>_GLOBAL
# ifdef <|PROJECT_UPCASE_IDENTIFIER|>_BUILD
#  define <|PROJECT_UPCASE_IDENTIFIER|>_GLOBAL    MULLE_C_GLOBAL
# else
#  if defined( <|PROJECT_UPCASE_IDENTIFIER|>_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( <|PROJECT_UPCASE_IDENTIFIER|>_INCLUDE_STATIC))
#   define <|PROJECT_UPCASE_IDENTIFIER|>_GLOBAL   MULLE_C_GLOBAL
#  else
#   define <|PROJECT_UPCASE_IDENTIFIER|>_GLOBAL   extern
#  endif
# endif
#endif

/* You can add some more include statements here */

#endif
